apiVersion: v1
kind: ReplicaController
metadata:
  name: mynginx-rc
spec:
   replicas: 2
   selctor:
    app: mynginx
template:
  metadata:
    labels:
      app: mynginx
  spec: 
    containers: 
    - name: mynginx-container
      image: nginx
      ports:
       - containerPort: 80
